services:
  - type: web
    name: squeezeweasel-api
    env: node
    buildCommand: pnpm install && pnpm prisma:generate && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

